USE [ORCHESTRA4700_TRUNK]
GO

/****** Object:  Table [dbo].[AU2_MATERIAL]    Script Date: 01.03.2020 15:17:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AU2_MATERIAL](
	[MATNR] [varchar](20) NOT NULL,
	[PRICE] [numeric](10, 2) NOT NULL,
	[DEFAULTTEXT] [varchar](255) NULL,
 CONSTRAINT [PK_AU2_MATERIAL] PRIMARY KEY CLUSTERED 
(
	[MATNR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[AU2_DETAIL_TEXT](
	[MATNR] [varchar](20) NOT NULL,
	[LANG] [varchar](10) NOT NULL,
	[TEXT] [varchar](255) NOT NULL,
 CONSTRAINT [PK_AU2_DETAIL_TEXT] PRIMARY KEY CLUSTERED 
(
	[MATNR] ASC,
	[LANG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AU2_DETAIL_TEXT]  WITH CHECK ADD  CONSTRAINT [FK_AU2_DETAIL_TEXT_AU2_MATERIAL] FOREIGN KEY([MATNR])
REFERENCES [dbo].[AU2_MATERIAL] ([MATNR])
GO

ALTER TABLE [dbo].[AU2_DETAIL_TEXT] CHECK CONSTRAINT [FK_AU2_DETAIL_TEXT_AU2_MATERIAL]
GO